ALTER TABLE DECLARATION RENAME COLUMN CURRENT_BALANCE TO CURRENT_BALANCE_PLN;
ALTER TABLE DECLARATION ADD COLUMN current_balance_eur NUMERIC(18, 2);

COMMENT ON COLUMN DECLARATION.CURRENT_BALANCE_PLN IS 'Saldo bieżące w chwili utworzenia lub aktualizacji deklaracji (PLN)';
COMMENT ON COLUMN DECLARATION.CURRENT_BALANCE_EUR IS 'Saldo bieżące w chwili utworzenia lub aktualizacji deklaracji (EUR)';

ALTER TABLE DECLARATION_AUD RENAME COLUMN CURRENT_BALANCE TO CURRENT_BALANCE_PLN;
ALTER TABLE DECLARATION_AUD ADD COLUMN current_balance_eur NUMERIC(18, 2);