export enum GetInvoicesSortEnum {
    ID = 'ID',
    DUE_DATE = 'DUE_DATE',
    ISSUE_DATE = 'ISSUE_DATE',
    LAST_PAYMENT_DATE = 'LAST_PAYMENT_DATE',
    CONTRACT_NUMBER = 'CONTRACT_NUMBER',
    NUMBER = 'NUMBER',
    CURRENCY = 'CURRENCY',
    CURRENT_BALANCE = 'CURRENT_BALANCE',
    PAID = 'PAID',
    EXCLUDED = 'EXCLUDED',
    GROSS_AMOUNT = 'GROSS_AMOUNT'
}
