DELETE FROM activity_type_detail_property_dict_value;
DELETE FROM activity_detail;
DELETE FROM activity_type_has_detail_property;
DELETE FROM activity_detail_property;
DELETE FROM default_issue_activity;
DELETE FROM declaration;
DELETE FROM activity;
DELETE FROM issue_invoice;
DELETE FROM invoice;
DELETE FROM issue_termination_request;
DELETE FROM issue_tag;
DELETE FROM issue;
DELETE FROM issue_type_transition;
DELETE FROM operator_type_issue_type;
DELETE FROM issue_type_configuration;
DELETE FROM issue_type_activity_type;
DELETE FROM issue_type;
DELETE FROM customer_out_of_service;
DELETE FROM contract_out_of_service;
DELETE FROM formal_debt_collection_customer_out_of_service;
DELETE FROM formal_debt_collection_contract_out_of_service;
DELETE FROM notification;
DELETE FROM contract;
DELETE FROM customer;
DELETE FROM postal_code_aud;
DELETE FROM postal_code;
DELETE FROM alwin_operator;
DELETE FROM permission;
DELETE FROM holiday;
DELETE FROM alwin_user;
DELETE FROM operator_type;
DELETE FROM activity_type;
DELETE FROM company_person;
DELETE FROM company_contact_detail;
DELETE FROM person_contact_detail;
DELETE FROM contact_detail;
DELETE FROM company_address;
DELETE FROM person_address;
DELETE FROM address;
DELETE FROM company;
DELETE FROM person;
DELETE FROM message_template;
DELETE FROM last_data_sync;
DELETE FROM person_aud;
DELETE FROM tag;
DELETE FROM scheduler_execution;
DELETE FROM scheduler_configuration;
DELETE FROM tag_icon;
DELETE FROM contract_termination_invoice;
DELETE FROM contract_termination_subject;
DELETE FROM contract_termination_has_attachment;
DELETE FROM contract_termination_attachment;
DELETE FROM contract_termination;
DELETE FROM demand_for_payment_invoice;
DELETE FROM formal_debt_collection_invoice;
DELETE FROM contract_termination_invoice_aud;
DELETE FROM contract_termination_subject_aud;
DELETE FROM contract_termination_has_attachment_aud;
DELETE FROM contract_termination_attachment_aud;
DELETE FROM contract_termination_aud;
DELETE FROM formal_debt_collection_invoice_aud;
DELETE FROM demand_for_payment;
DELETE FROM demand_for_payment_type_configuration;
-- sequence restart from 100
ALTER SEQUENCE postal_code_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE person_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE invoice_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE address_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE contract_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE permission_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE notification_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE contact_detail_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE message_template_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE customer_out_of_service_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE contract_out_of_service_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE issue_termination_request_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE demand_for_payment_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE holiday_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE tag_id_seq START 100 RESTART WITH 100 MINVALUE 100;
ALTER SEQUENCE scheduler_execution_id_seq START 100 RESTART 100 MINVALUE 100;
ALTER SEQUENCE issue_tag_id_seq START 100 RESTART 100 MINVALUE 100;
ALTER SEQUENCE scheduler_configuration_id_seq START 100 RESTART 100 MINVALUE 100;
ALTER SEQUENCE issue_type_activity_type_id_seq START 100 RESTART 100 MINVALUE 100;
ALTER SEQUENCE default_issue_activity_id_seq START 100 RESTART 100 MINVALUE 100;
ALTER SEQUENCE activity_type_has_detail_property_id_seq START 100 RESTART 100 MINVALUE 100;
ALTER SEQUENCE activity_type_detail_property_dict_value_id_seq START 100 RESTART 100 MINVALUE 100;
ALTER SEQUENCE contract_termination_id_seq START 100 RESTART 100 MINVALUE 100;
ALTER SEQUENCE contract_termination_subject_id_seq START 100 RESTART 100 MINVALUE 100;
ALTER SEQUENCE formal_debt_collection_invoice_id_seq START 100 RESTART 100 MINVALUE 100;
ALTER SEQUENCE contract_termination_attachment_id_seq START 100 RESTART 100 MINVALUE 100;
-- sequence restart from 1
ALTER SEQUENCE activity_id_seq START 1 RESTART WITH 1 MINVALUE 1;
ALTER SEQUENCE declaration_id_seq START 1 RESTART WITH 1 MINVALUE 1;
ALTER SEQUENCE activity_detail_id_seq START 1 RESTART WITH 1 MINVALUE 1;
ALTER SEQUENCE tag_icon_id_seq START 1 RESTART 1 MINVALUE 1;
