create index idx_customer_alwin_operator on customer (account_manager_id);
create index idx_issue_issue_type_id on issue (issue_type_id);
create index idx_issue_termination_operator_id on issue (termination_operator_id);
create index idx_child_issue_type_id on issue_type_transition (child_issue_type_id);
create index idx_closed_issue_type_id on issue_type_transition (closed_issue_type_id);
create index idx_activity_type on default_issue_activity (activity_type_id);
create index idx_issue_type on default_issue_activity (issue_type_id);
create index idx_issue_invoice_invoice on issue_invoice(invoice_id);
create index idx_operator_type_parent_operator_type_id on operator_type (parent_operator_type_id);
create index idx_alwin_operator_alwin_operator on alwin_operator (parent_alwin_operator_id);
create index idx_alwin_operator_alwin_user on alwin_operator (alwin_user_id);
create index idx_alwin_operator_operator_type on alwin_operator (operator_type_id);
create index idx_alwin_operator_permission on alwin_operator (permission_id);
create index idx_operator_type_issue_type_issue_type on operator_type_issue_type (issue_type_id);
create index idx_operator_type_issue_type_operator_type on operator_type_issue_type (operator_type_id);
create index idx_8pavhn1oejo2hbfyi0wwxlhk7 on address_aud (rev);
create index idx_avlit4ky8rlvoiku0y2ew9o7 on company_aud (rev);
create index idx_eshw37x9pafh93xdx81gb6vno on contact_detail_aud (rev);
create index idx_6m0ndyymbd03jgiq8o9qa3e65 on person_aud (rev);
create index idx_aj3jrmqx0w728g0ueq4orx35c on activity_aud (rev);
create index idx_rp74up6w4fj2yaiugck26ybcj on activity_detail_aud (rev);
create index idx_gfdldd57t34nbv0afk259oncb on activity_detail_property_aud (rev);
create index idx_5kahvwyqtjg1lsf6nd77w0q6s on activity_type_aud (rev);
create index idx_2hdmkbnit7lf7amkxtig2bbbo on activity_type_has_detail_property_aud (rev);
create index idx_sj2com32ttjd08bfv9h28p87f on alwin_operator_aud (rev);
create index idx_ih515lnkismggrtfoq7hdnvne on alwin_user_aud (rev);
create index idx_f9tfq0prxe8vbsau3bpbmlcya on contract_aud (rev);
create index idx_meoyvv2wyms32m3q8xrby1lox on customer_aud (rev);
create index idx_nyupmn62uvjwcpb85jrjxl8ox on declaration_aud (rev);
create index idx_99r0ko1ns7art19gyloh1tsrc on issue_aud (rev);
create index idx_2vp072py05tlvikbnoa17pi6t on invoice_aud (rev);
create index idx_1skel0aisimn0sje8mf3jetf6 on issue_type_aud (rev);
create index idx_ran0g8nleqr6b22slrcnq3859 on operator_type_aud (rev);
create index idx_hgrao1tyqi2ai2pyrq7n9r09q on permission_aud (rev);
create index idx_issue_termination_request_issue on issue_termination_request (issue_id);
create index idx_issue_termination_request_manager_operator on issue_termination_request (manager_operator_id);
create index idx_issue_termination_request_request_operator on issue_termination_request (request_operator_id);
create index idx_demand_for_payment_preceding_demand_for_payment_id on demand_for_payment (preceding_demand_for_payment_id);
create index idx_demand_for_payment_type_configuration on demand_for_payment (demand_for_payment_type_configuration_id);
create index idx_holiday_alwin_user_id on holiday (alwin_user_id);
create index idx_tag_tag_icon on tag (tag_icon_id);
create index idx_issue_tag_issue_id on issue_tag (issue_id);
create index idx_issue_tag_tag_id on issue_tag (tag_id);
create index idx_issue_type_activity_type_activity_type_id on issue_type_activity_type (activity_type_id);
create index idx_issue_type_activity_type_issue_type_id on issue_type_activity_type (issue_type_id);
create index idx_contract_termination_preceding_contract_termination_id on contract_termination (preceding_contract_termination_id);
create index idx_contract_termination_preceding_demand_for_payment_id on contract_termination (preceding_demand_for_payment_id);
create index idx_contract_termination on contract_termination_subject (contract_termination_id);
create index idx_formal_debt_collection_invoice_invoice on contract_termination_invoice (formal_debt_collection_invoice_id);
create index idx_demand_for_payment_invoice_invoice on demand_for_payment_invoice (formal_debt_collection_invoice_id);
create index idx_contract_termination_attachment on contract_termination_has_attachment (contract_termination_attachment_id);
create index idx_postal_code_alwin_operator on postal_code (operator_id);

create index idx_activity_activity_state on activity(activity_state);
create index idx_activity_detail_property_property_type on activity_detail_property(property_type);
create index idx_activity_type_has_detail_property_state on activity_type_has_detail_property(state);
create index idx_contract_termination_state on contract_termination(state);
create index idx_contract_termination_type on contract_termination(type);
create index idx_demand_for_payment_state on demand_for_payment(state);
create index idx_formal_debt_collection_contract_out_of_service_demand_for_payment_type on formal_debt_collection_contract_out_of_service(demand_for_payment_type);
create index idx_formal_debt_collection_customer_out_of_service_demand_for_payment_type on formal_debt_collection_customer_out_of_service(demand_for_payment_type);
create index idx_issue_issue_state on issue(issue_state);
create index idx_issue_termination_request_state on issue_termination_request(state);
create index idx_scheduler_execution_type on scheduler_execution(type);
create index idx_tag_tag_type on tag(tag_type);

REINDEX  INDEX idx_customer_alwin_operator;
REINDEX  INDEX idx_issue_issue_type_id;
REINDEX  INDEX idx_issue_termination_operator_id;
REINDEX  INDEX idx_child_issue_type_id;
REINDEX  INDEX idx_closed_issue_type_id;
REINDEX  INDEX idx_activity_type;
REINDEX  INDEX idx_issue_type;
REINDEX  INDEX idx_issue_invoice_invoice;
REINDEX  INDEX idx_operator_type_parent_operator_type_id;
REINDEX  INDEX idx_alwin_operator_alwin_operator;
REINDEX  INDEX idx_alwin_operator_alwin_user;
REINDEX  INDEX idx_alwin_operator_operator_type;
REINDEX  INDEX idx_alwin_operator_permission;
REINDEX  INDEX idx_operator_type_issue_type_issue_type;
REINDEX  INDEX idx_operator_type_issue_type_operator_type;
REINDEX  INDEX idx_8pavhn1oejo2hbfyi0wwxlhk7;
REINDEX  INDEX idx_avlit4ky8rlvoiku0y2ew9o7;
REINDEX  INDEX idx_eshw37x9pafh93xdx81gb6vno;
REINDEX  INDEX idx_6m0ndyymbd03jgiq8o9qa3e65;
REINDEX  INDEX idx_aj3jrmqx0w728g0ueq4orx35c;
REINDEX  INDEX idx_rp74up6w4fj2yaiugck26ybcj;
REINDEX  INDEX idx_gfdldd57t34nbv0afk259oncb;
REINDEX  INDEX idx_5kahvwyqtjg1lsf6nd77w0q6s;
REINDEX  INDEX idx_2hdmkbnit7lf7amkxtig2bbbo;
REINDEX  INDEX idx_sj2com32ttjd08bfv9h28p87f;
REINDEX  INDEX idx_ih515lnkismggrtfoq7hdnvne;
REINDEX  INDEX idx_f9tfq0prxe8vbsau3bpbmlcya;
REINDEX  INDEX idx_meoyvv2wyms32m3q8xrby1lox;
REINDEX  INDEX idx_nyupmn62uvjwcpb85jrjxl8ox;
REINDEX  INDEX idx_99r0ko1ns7art19gyloh1tsrc;
REINDEX  INDEX idx_2vp072py05tlvikbnoa17pi6t;
REINDEX  INDEX idx_1skel0aisimn0sje8mf3jetf6;
REINDEX  INDEX idx_ran0g8nleqr6b22slrcnq3859;
REINDEX  INDEX idx_hgrao1tyqi2ai2pyrq7n9r09q;
REINDEX  INDEX idx_issue_termination_request_issue;
REINDEX  INDEX idx_issue_termination_request_manager_operator;
REINDEX  INDEX idx_issue_termination_request_request_operator;
REINDEX  INDEX idx_demand_for_payment_preceding_demand_for_payment_id;
REINDEX  INDEX idx_demand_for_payment_type_configuration;
REINDEX  INDEX idx_holiday_alwin_user_id;
REINDEX  INDEX idx_tag_tag_icon;
REINDEX  INDEX idx_issue_tag_issue_id;
REINDEX  INDEX idx_issue_tag_tag_id;
REINDEX  INDEX idx_issue_type_activity_type_activity_type_id;
REINDEX  INDEX idx_issue_type_activity_type_issue_type_id;
REINDEX  INDEX idx_contract_termination_preceding_contract_termination_id;
REINDEX  INDEX idx_contract_termination_preceding_demand_for_payment_id;
REINDEX  INDEX idx_contract_termination;
REINDEX  INDEX idx_formal_debt_collection_invoice_invoice;
REINDEX  INDEX idx_demand_for_payment_invoice_invoice;
REINDEX  INDEX idx_contract_termination_attachment;
REINDEX  INDEX idx_postal_code_alwin_operator;
REINDEX  INDEX idx_activity_activity_state;
REINDEX  INDEX idx_activity_detail_property_property_type;
REINDEX  INDEX idx_activity_type_has_detail_property_state;
REINDEX  INDEX idx_contract_termination_state;
REINDEX  INDEX idx_contract_termination_type;
REINDEX  INDEX idx_demand_for_payment_state;
REINDEX  INDEX idx_formal_debt_collection_contract_out_of_service_demand_for_payment_type;
REINDEX  INDEX idx_formal_debt_collection_customer_out_of_service_demand_for_payment_type;
REINDEX  INDEX idx_issue_issue_state;
REINDEX  INDEX idx_issue_termination_request_state;
REINDEX  INDEX idx_scheduler_execution_type;
REINDEX  INDEX idx_tag_tag_type;