
export enum GetIssuesSortEnum {
    CUSTOMER = 'CUSTOMER',
    START_DATE = 'START_DATE',
    EXPIRATION_DATE = 'EXPIRATION_DATE',
    TYPE = 'TYPE',
    STATE = 'STATE',
    BALANCE_START = 'BALANCE_START',
    CURRENT_BALANCE = 'CURRENT_BALANCE',
    PAYMENTS = 'PAYMENTS'
}

export enum GetActivitiesIssue {
    ID = 'ID',
    STATE = 'STATE',
    TYPE = 'TYPE',
    TYPE_NAME = 'TYPE_NAME',
    REMARK = 'REMARK',
    OPERATOR = 'OPERATOR',
    OPERATOR_FIRST_NAME = 'OPERATOR_FIRST_NAME',
    OPERATOR_LAST_NAME = 'OPERATOR_LAST_NAME',
    CREATION_DATE = 'CREATION_DATE',
    ACTIVITY_DATE = 'ACTIVITY_DATE',
    PLANNED_DATE = 'PLANNED_DATE'
}

export enum GetFieldDebtIssues {
    ID = 'ID',
    CUSTOMER = 'CUSTOMER',
    START_DATE = 'START_DATE',
    EXPIRATION_DATE = 'EXPIRATION_DATE',
    TYPE = 'TYPE',
    STATE = 'STATE',
    PRIORITY_STATE = 'PRIORITY_STATE',
    RPB = 'RPB',
    RPB_PLN = 'RPB_PLN',
    RPB_EUR = 'RPB_EUR',
    BALANCE_START = 'BALANCE_START',
    BALANCE_START_PLN = 'BALANCE_START_PLN',
    BALANCE_START_EUR = 'BALANCE_START_EUR',
    CURRENT_BALANCE = 'CURRENT_BALANCE',
    CURRENT_BALANCE_PLN = 'CURRENT_BALANCE_PLN',
    CURRENT_BALANCE_EUR = 'CURRENT_BALANCE_EUR',
    PAYMENTS = 'PAYMENTS',
    PAYMENTS_PLN = 'PAYMENTS_PLN',
    PAYMENTS_EUR = 'PAYMENTS_EUR',
    EXT_COMPANY_ID = 'EXT_COMPANY_ID'
}


export enum GetManagedIssues {
    ID = 'ID',
    CUSTOMER = 'CUSTOMER',
    START_DATE = 'START_DATE',
    EXPIRATION_DATE = 'EXPIRATION_DATE',
    TYPE = 'TYPE',
    STATE = 'STATE',
    PRIORITY_STATE = 'PRIORITY_STATE',
    RPB = 'RPB',
    RPB_PLN = 'RPB_PLN',
    RPB_EUR = 'RPB_EUR',
    BALANCE_START = 'BALANCE_START',
    BALANCE_START_PLN = 'BALANCE_START_PLN',
    BALANCE_START_EUR = 'BALANCE_START_EUR',
    CURRENT_BALANCE = 'CURRENT_BALANCE',
    CURRENT_BALANCE_PLN = 'CURRENT_BALANCE_PLN',
    CURRENT_BALANCE_EUR = 'CURRENT_BALANCE_EUR',
    PAYMENTS = 'PAYMENTS',
    PAYMENTS_PLN = 'PAYMENTS_PLN',
    PAYMENTS_EUR = 'PAYMENTS_EUR',
    EXT_COMPANY_ID = 'EXT_COMPANY_ID'
}
