ALTER TABLE ISSUE
  ADD COLUMN ISSUE_TYPE_ID BIGINT;

COMMENT ON COLUMN ISSUE.ISSUE_TYPE_ID IS 'Typ zlecenia';

UPDATE ISSUE
SET ISSUE_TYPE_ID = ((SELECT it.ID
                      FROM ISSUE_TYPE it
                      WHERE it.NAME = 'PHONE_DEBT_COLLECTION_1'));

ALTER TABLE ISSUE
  ADD CONSTRAINT fk_issue_issue_type_id
FOREIGN KEY (ISSUE_TYPE_ID)
REFERENCES ISSUE_TYPE (ID);

ALTER TABLE ISSUE
  ALTER ISSUE_TYPE_ID SET NOT NULL;

ALTER TABLE ISSUE
  DROP COLUMN ISSUE_TYPE;

UPDATE ISSUE_TYPE_TRANSITION
SET condition = 'NONE'
WHERE condition = 'none';

UPDATE ISSUE_TYPE_TRANSITION
SET condition = 'SECURED_ITEM'
WHERE condition = 'securedItem';

UPDATE ISSUE_TYPE_TRANSITION
SET condition = 'NON_SECURED_ITEM'
WHERE condition = 'nonSecuredItem';