ALTER TABLE PERMISSION ADD COLUMN allowed_to_terminate_issue BOOLEAN NOT NULL;
ALTER TABLE PERMISSION ADD COLUMN allowed_to_exclude_invoice BOOLEAN NOT NULL;

ALTER TABLE PERMISSION_AUD ADD COLUMN allowed_to_terminate_issue BOOLEAN NOT NULL;
ALTER TABLE PERMISSION_AUD ADD COLUMN allowed_to_exclude_invoice BOOLEAN NOT NULL;