ALTER TABLE DECLARATION RENAME COLUMN CASH_PAID TO CASH_PAID_PLN;
ALTER TABLE DECLARATION ADD COLUMN CASH_PAID_EUR NUMERIC(18, 2);

COMMENT ON COLUMN DECLARATION.CASH_PAID_PLN IS 'Kwota dokonanej wpłaty (PLN)';
COMMENT ON COLUMN DECLARATION.CASH_PAID_EUR IS 'Kwota dokonanej wpłaty (EUR)';

ALTER TABLE DECLARATION_AUD RENAME COLUMN CASH_PAID TO CASH_PAID_PLN;
ALTER TABLE DECLARATION_AUD ADD COLUMN CASH_PAID_EUR NUMERIC(18, 2);