package com.codersteam.alwin.common.scheduler;

/**
 * Typ zadania cyklicznego
 */
public enum SchedulerTaskType {
    UPDATE_BALANCE_AND_CLOSE_EXPIRED_AND_CREATE_CHILD_ISSUES,
    UPDATE_ISSUES_BALANCE,
    UPDATE_DECLARATIONS_BALANCE,
    GENERATE_ISSUES,
    CLOSE_EXPIRED_ISSUES_AND_CREATE_CHILD_ISSUES_IF_NEEDED,
    FIND_MISSING_ISSUES_AND_SEND_REPORT_EMAIL,
    UPDATE_COMPANY_DATA,
    UPDATE_COMPANIES_INVOLVEMENT,
    FIND_UNRESOLVED_ISSUES_AND_SEND_REPORT_EMAIL,
    CREATE_OUTGOING_CALL_ACTIVITY,
    TAG_OVERDUE_ISSUES,
    GENERATE_DEMAND_FOR_PAYMENT_AND_CONTRACT_TERMINATION
}
