-- segment A, extCompanyId = 6627, WT1
UPDATE FAKTURA
SET PLATNOSCDATA = trunc(SYSDATE - 1)
WHERE FAKTURANO = 69134;
-- segment A, extCompanyId = 7861, WT2
UPDATE FAKTURA
SET PLATNOSCDATA = trunc(SYSDATE - 16)
WHERE FAKTURANO = 69318;
-- segment A, extCompanyId = 7044, WT2
UPDATE FAKTURA
SET PLATNOSCDATA = trunc(SYSDATE - 1)
WHERE FAKTURANO = 62295;
UPDATE FAKTURA
SET PLATNOSCDATA = trunc(SYSDATE - 16)
WHERE FAKTURANO = 62640;
-- segment B, extCompanyId = 8046, WT1
UPDATE Contract
SET SIGNDATE = TRUNC(SYSDATE - 100)
WHERE id = 6606;
UPDATE FAKTURA
SET PLATNOSCDATA = trunc(SYSDATE - 1)
WHERE FAKTURANO = 69388;
-- segment B, extCompanyId = 8081, WT2
UPDATE Contract
SET SIGNDATE = TRUNC(SYSDATE - 100)
WHERE id = 6651;
UPDATE FAKTURA
SET PLATNOSCDATA = trunc(SYSDATE - 11)
WHERE FAKTURANO = 68581;
-- segment B, extCompanyId = 7254, WT2
UPDATE Contract
SET SIGNDATE = TRUNC(SYSDATE - 100)
WHERE id = 5969;
UPDATE FAKTURA
SET PLATNOSCDATA = trunc(SYSDATE - 1)
WHERE FAKTURANO = 64038;
UPDATE FAKTURA
SET PLATNOSCDATA = trunc(SYSDATE - 11)
WHERE FAKTURANO = 64039
